In [1]:
!pip3 install numpy

In [1]:
import numpy as np

In [2]:
arr=np.array([1, 2, 3, 4, 5])
print(arr, type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [3]:
import time


In [4]:
# execution performance
size=1_000_000
start=time.time()
py_list=list(range(size))
sq_list=[x**2 for x in py_list]
end=time.time()
print(f"python list time = {end-start}seconds")

# numpy arrays
np_arr=np.array(py_list)
start=time.time()
sqr_arr=np_arr ** 2
end=time.time()
print(f"numpy array time = {end-start}seconds")

python list time = 0.1516249179840088seconds
numpy array time = 0.0038874149322509766seconds


In [13]:
# memory

import sys
print(f"python list size={sys.getsizeof(py_list)*len(py_list)} bytes")

print(f"numpy list size={np_arr.nbytes} bytes")

python list size=8000056000000 bytes
numpy list size=8000000 bytes


In [9]:
# create from lists 
# 1d list 
# in 1d list shape means total number element 
import numpy as np
arr1=np.array([1, 2, 3, 4, 5])
print(arr1,type(arr1), arr1.dtype, arr1.shape)
arr2=np.array([1, 2, 3, 4, 5, "prime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

# 2d array
arr2d=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d, arr2d.shape)
# in 2d list shape shows the number of rows and columns
# 2d list simply a matrix having m rows and n columns


[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [15]:
# create
arr1=np.zeros((2, 3), dtype="int64")# prefill - create zero matrix of 2x3
print(arr1, arr1.shape)

arr2=np.ones((3 ,3))# prefill - create A matrix having all element == 1
print(arr1, arr2.shape)

arr3=np.full((3, 4), 100) # prefill with value(100)
print(arr3, arr3.shape)

arr4=np.eye(3)# identity matrix- m==n  and diagonal matrix == 1
print(arr4, arr4.shape)

# range(start, end, step)
arr5=np.arange(1, 11, 2) # range elements
print(arr5)

arr6=np.linspace(1, 100, 3)# evenly spaced arrays - (start, end, no of element)
print(arr6)

[[0 0 0]
 [0 0 0]] (2, 3)
[[0 0 0]
 [0 0 0]] (3, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 3 5 7 9]
[  1.   50.5 100. ]


In [20]:
# properties
arr=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr.shape)# dimension = m x n
print(arr.size)# total element - 9
print(arr.dtype)# data types 
print(arr.ndim)# no of dimension

# typecasting
float_arr=arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [29]:
# operations on array

# reshaping
arr=np.array([[1,2,3], [4,5,6]])
print(arr, arr.shape)

reshaped=arr.reshape((3, 2))
print(reshaped, reshaped.shape)

# flattened array= convert it into 1d
flattened=arr.flatten()# 2D =>1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [39]:
# indexing
arr=np.array([1, 2, 3, 4, 5])
print(arr[0])# 1
print(arr[3])# 4
arr1=np.array([[1,2,3], [4,5,6]])
print(arr1[1][1])# 5- element on 1 row and 1 column 

# Fancy indexing
arr2=np.array([1, 2, 3, 4, 5])
idx=[0, 1, 3]
print(arr2[idx])#[1 2 4]= [value at index 1, at index 2 , at index 4]

# bolean indexing
print(arr2[arr > 2])# print the element whose value > 2
print(arr2[arr % 2==0])# all even value 
print(arr2[arr % 2!=0])# all odd value

#slicing- same as list slicing
arr=np.array([1, 2, 3, 4, 5])
print(arr[1:4])
print(arr[1:])
print(arr[:])
print(arr[::2])
print(arr[::-1])

1
4
5
[1 2 4]
[3 4 5]
[2 4]
[1 3 5]
[2 3 4]
[2 3 4 5]
[1 2 3 4 5]
[1 3 5]
[5 4 3 2 1]


In [41]:
# difference between numpy slicing and list slicing
"""
numpy array print a part or a view of the parent array but python 
list create sub list of parent list that means changes in sublist not affect 
current list but in numpy array it's not like that  because after slicing, the 
output is part of the parent elements so when we change it, original array 
also change"""

# example:-
# python list
nums=[1,2,3,4]
sub_list=nums[1:3]
print(sub_list)
sub_list[0]=200
print(sub_list)
print(nums)

# numpy array
arr=np.array([1,2,3,4])
sub_arr=arr[1:3]
print(sub_arr)
sub_arr[0]=200
print(sub_arr)
print(arr)

[2, 3]
[200, 3]
[1, 2, 3, 4]
[2 3]
[200   3]
[  1 200   3   4]


In [4]:
# datatypes

# Integers:- int32, in64, 64,32 shows no of bits 
# floating point nums: float32, float64
# boolean-bool
# Complex nums- complex64, complex128
# string:- $(byte-str) U(unicode-str)
# object:generic python objects - object
import numpy as np
# create complex number 
arr1=np.array([3 + 5j])
arr2=np.array([2 + 3j])
print(arr1 + arr2)
print(arr1 - arr2)
arr=np.array(["prime", {1, 2, 3}, 3.14])
print(arr, arr.dtype)

[5.+8.j]
[1.+2.j]
['prime' {1, 2, 3} 3.14] object


In [10]:
# Axes in multi-dimensional arrays

# 1D ---> 1 Axes (axis 0)
# 2D ---> 2 Axes ((axis 0)- column)- perform vertically operations ,((axis 1)- rows)- perform horizontally operations
# 3D ---> 3 Axes ((axis 0)- depth or no of layers), ((axis 1)- row in each layers), ((axis 2)- column each layer)
# to store colorfull picture we need to store the value of r(red) g(green) b(blue) in 3d r store in axes 0 g store in axes 1 and b store in axes 2
arr2d=np.array([[1,2,3], [4,5,6],[7,8,9]])
print(arr2d)
print(np.sum(arr2d))
# calculate sum of column
sum_of_columns=np.sum(arr2d, axis=0)
print(sum_of_columns)
# calculate sum of rows in 2d array
sum_of_rows=np.sum(arr2d, axis=1)
print(sum_of_rows)

# slicing in 2d array
print(arr2d[0:2, 1:2])
#            |     |
#          rows  columns

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [15]:
# 3D array
arr3d=np.array([[[1, 2], [3 ,4], [5, 6]], [[7, 8], [9, 10], [11, 12]]])
print(arr3d, arr3d.shape) # first matrix - 3 x 2 second matrix - 3 x 2
# total size - 2 x 3 x 2 (column of matrix 1, row of both matrix, column of matrix 2) 

# indexing
# arr[axes, row, column]
print(arr3d[0 ,1, 1])

# slicing
print(arr3d[:, 0, :])# first row of both columns
print(arr3d[:, :, 0])# first column of both columns

# data manipulating
arr3d[:, 0, :]=99 # change all the value of first row in columns
print(arr3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [4]:
# vectorization
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

print(arr1+arr2)

[ 7  9 11 13 15]


In [10]:
# broadcasting
arr1=np.array([1,2,3,4,5])
print(arr1.shape)

arr2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr2.shape)
print(arr1+arr2)

# arr3=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
# print(arr3+arr2)# show error
# here broadcasting not work


(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [11]:
# normalization
arr=np.array([[1,2],[3,4]])
mean=np.mean(arr)
std_dev=np.std(arr)
normalized_arr=(arr-mean)/std_dev # formula for finding normalized form
print(normalized_arr)
print(mean)# mean=sum of all value/ total number of values
print(std_dev) # std_dev = under root of ((sum of (sqr of every (arr-mean))/total number of values))


[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [15]:
# important mathematical function

# aggregation function- singlr value in output
arr=np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.std(arr))# dtandard deviation- cover on previous cell
print(np.median(arr))
print(np.var(arr))# variance-(sum of (sqr of every (arr-mean))/total number of values)

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [14]:
# power function
arr=np.array([1,2,3,4,5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.power(arr, 3))


[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [18]:
# log, exponentional function
arr=np.array([1,2,3,4,5])
print(np.log(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [23]:
# Roundiing value
print(np.round(3.14)) # round .5+ round up,.5- round down
print(np.ceil(3.14))# round up
print(np.floor(3.14))# round down
print(np.trunc(9.9))# cut the value after the decimal

# unique function
arr=np.array([1, 2, 3, -4, 5, 4, 3, 2, 5])
print(np.unique(arr))
print(np.sort(arr)) # asccending order
print(np.abs(arr)) # convert negative value to positive value


3.0
4.0
3.0
9.0
[-4  1  2  3  4  5]
[-4  1  2  2  3  3  4  5  5]
[1 2 3 4 5 4 3 2 5]
